baseURL = 'https://snyt45.com/'
languageCode = 'ja'
title = 'Small Changes'
copyright = 'snyt45'
googleAnalytics = "G-FFNLJVXS4C"
DefaultContentLanguage = 'ja'
hasCJKLanguage = true

[pagination]
pagerSize = 5

[permalinks]
post = "/post/:year/:slug/"
